### ISSUE TITLE
Filter Historical Episode list By Start/End date

### ISSUE THREAD

**Issue by runrobrun** [WPU-APCS-370/ahcer-episode-recorder#5]
As a parent/care giver
I would like to be able to filter the report by a specific date
SO I can view only wanted records

Tech notes:
we would provide two search boxes at the top of the table From date: (datepicker) To date: (datepicker) and a 'go' button.
When the go button is clicked then the search will return episodes between the given dates.

**Comment by KaungHT13** [comment]
https://ux.stackexchange.com/a/136890
